### ISSUE TITLE
set up Travis build

### ISSUE THREAD

**Issue by hawkw** [sos-os/hal9000#1]
Right now, our Travis build is failing for this repo because we don't have a `.travis.yml`, so it assumes this is a Ruby project. We should do something about that:
- [ ] add `.travis.yml` with basic Rust configuration
- [ ] add Travis badge to README

**Comment by hawkw** [comment]
FYI, as far as I can tell, I think the travis configuration for this repo can be as simple as 
```yaml
language: rust
rust: nightly
```
if that doesn't build successfully, we can look into what else is necessary.

Might be worth building against both `nightly` and `stable` eventually, but if we do, the `stable` build should be allowed to fail.

**Comment by hawkw** [comment]
Docs publishing might be nice as well, since this is a library on which a lot of other SOS projects will eventually depend upon, but should probably be another issue.

**Comment by Atul9** [comment]
Hi @hawkw I would like to work on this
